package loyaltyusecase

import (
	"context"
	"fmt"

	"cashflow_backend/internal/domain/loyalty"
	"cashflow_backend/internal/domain/sale"
	platformerrors "cashflow_backend/internal/platform/errors"
	"cashflow_backend/internal/platform/filter"
	"cashflow_backend/internal/platform/pagination"
)

// SettleOrder finalises the loyalty impact of a confirmed sales order:
//   - Credits the earned points projected on applied coupons (current & both)
//     to the card balance together with a history entry.
//   - Credits future-program cards generated by EarnCoupons for this order.
//   - Cleans the projection rows.
func (uc *UseCase) SettleOrder(ctx context.Context, order *sale.SaleOrder) error {
	if uc.repo == nil {
		return platformerrors.Internal("loyalty repository is not configured", nil)
	}
	if order == nil {
		return nil
	}

	projections, err := uc.repo.ListCouponPointsByOrder(ctx, order.ID)
	if err != nil {
		return err
	}

	settled := map[int64]bool{}
	for _, proj := range projections {
		card, err := uc.repo.GetCardByID(ctx, proj.CouponID)
		if err != nil {
			return err
		}
		if card == nil {
			continue
		}
		card.Points += proj.Points
		card.UseCount++
		if err := uc.repo.UpdateCard(ctx, card); err != nil {
			return err
		}
		settled[card.ID] = true
		if err := uc.repo.AddHistory(ctx, &loyalty.LoyaltyHistory{
			CardID:      card.ID,
			CompanyID:   card.CompanyID,
			Description: fmt.Sprintf("Points earned on confirmed order %s", order.Name),
			Issued:      proj.Points,
			OrderModel:  "sale.order",
			OrderID:     &order.ID,
		}); err != nil {
			return err
		}
		uc.logger.InfoContext(ctx, "loyalty points credited on confirm",
			"order_id", order.ID, "coupon_id", card.ID, "points", proj.Points)
	}

	// Deduct the points consumed by reward lines from their coupons.
	consumedByCoupon := map[int64]float64{}
	for _, l := range order.Lines {
		if l.IsRewardLine && l.CouponID != nil && l.PointsCost > 0 {
			consumedByCoupon[*l.CouponID] += l.PointsCost
		}
	}
	for couponID, consumed := range consumedByCoupon {
		card, err := uc.repo.GetCardByID(ctx, couponID)
		if err != nil {
			return err
		}
		if card == nil {
			continue
		}
		card.Points -= consumed
		if card.Points < 0 {
			card.Points = 0
		}
		if !settled[card.ID] {
			card.UseCount++
		}
		if err := uc.repo.UpdateCard(ctx, card); err != nil {
			return err
		}
		if err := uc.repo.AddHistory(ctx, &loyalty.LoyaltyHistory{
			CardID:      card.ID,
			CompanyID:   card.CompanyID,
			Description: fmt.Sprintf("Points used on confirmed order %s", order.Name),
			Used:        consumed,
			OrderModel:  "sale.order",
			OrderID:     &order.ID,
		}); err != nil {
			return err
		}
	}

	// Projection rows are intentionally kept after settlement so that a later
	// cancel can reverse the credited earnings; ReverseOrder clears them.
	uc.logger.InfoContext(ctx, "loyalty order settled", "order_id", order.ID, "coupon_count", len(projections))
	return nil
}

// ReverseOrder undoes the loyalty impact when a confirmed order is cancelled:
//   - Refunds the points consumed by reward lines back to their coupons.
//   - Debits the points earned on applied coupons minus the refunded amount.
//   - Deletes unused future-program cards generated for this order.
func (uc *UseCase) ReverseOrder(ctx context.Context, order *sale.SaleOrder) error {
	if uc.repo == nil || order == nil {
		return nil
	}

	// Refund consumed reward points.
	refundByCoupon := map[int64]float64{}
	for _, l := range order.Lines {
		if l.IsRewardLine && l.CouponID != nil && l.PointsCost > 0 {
			refundByCoupon[*l.CouponID] += l.PointsCost
		}
	}
	for couponID, refund := range refundByCoupon {
		card, err := uc.repo.GetCardByID(ctx, couponID)
		if err != nil {
			return err
		}
		card.Points += refund
		if card.UseCount > 0 {
			card.UseCount--
		}
		if err := uc.repo.UpdateCard(ctx, card); err != nil {
			return err
		}
		if err := uc.repo.AddHistory(ctx, &loyalty.LoyaltyHistory{
			CardID:      card.ID,
			CompanyID:   card.CompanyID,
			Description: fmt.Sprintf("Points refunded - order %s cancelled", order.Name),
			Issued:      refund,
			OrderModel:  "sale.order",
			OrderID:     &order.ID,
		}); err != nil {
			return err
		}
	}

	// Projections for non-future coupons are still present when the confirm-time
	// settle was never triggered; drop them and debit credited balances when the
	// earning had already been finalised.
	projections, err := uc.repo.ListCouponPointsByOrder(ctx, order.ID)
	if err != nil {
		return err
	}
	for _, proj := range projections {
		card, err := uc.repo.GetCardByID(ctx, proj.CouponID)
		if err != nil {
			return err
		}
		card.Points -= proj.Points
		if card.Points < 0 {
			card.Points = 0
		}
		if err := uc.repo.AddHistory(ctx, &loyalty.LoyaltyHistory{
			CardID:      card.ID,
			CompanyID:   card.CompanyID,
			Description: fmt.Sprintf("Points reversed - order %s cancelled", order.Name),
			Used:        proj.Points,
			OrderModel:  "sale.order",
			OrderID:     &order.ID,
		}); err != nil {
			return err
		}
		if err := uc.repo.UpdateCard(ctx, card); err != nil {
			return err
		}
	}
	if err := uc.repo.RemoveCouponPointsByOrder(ctx, order.ID); err != nil {
		return err
	}
	return uc.deactivateUnusedGeneratedCards(ctx, order)
}

// ReleaseOrder cleans up the loyalty projection rows and generated future cards
// of an order that was cancelled before any settlement happened (e.g. a draft
// or sent quotation). No card balances are touched because they were never
// credited for this order.
func (uc *UseCase) ReleaseOrder(ctx context.Context, order *sale.SaleOrder) error {
	if uc.repo == nil || order == nil {
		return nil
	}
	if err := uc.repo.RemoveCouponPointsByOrder(ctx, order.ID); err != nil {
		return err
	}
	uc.logger.InfoContext(ctx, "loyalty order released", "order_id", order.ID)
	return uc.deactivateUnusedGeneratedCards(ctx, order)
}

// deactivateUnusedGeneratedCards disables future-program cards that were
// generated for an order and never accumulated a balance.
func (uc *UseCase) deactivateUnusedGeneratedCards(ctx context.Context, order *sale.SaleOrder) error {
	f := filter.NewFilter(filter.Criterion{Field: "order_id", Operator: filter.OpEqual, Value: order.ID})
	cards, err := uc.repo.ListCards(ctx, f, pagination.PageRequest{Limit: 100})
	if err != nil {
		return nil
	}
	for _, card := range cards.Items {
		if card.OrderID != nil && *card.OrderID == order.ID && card.Points <= 0.0001 {
			card.Active = false
			_ = uc.repo.UpdateCard(ctx, &card)
		}
	}
	return nil
}